#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and responds to SIGTERM

# Set up signal handler for SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
